server:
  port: 7001

eureka:
  instance:
    hostname: localhost # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向Eureka注册中心注册自己
    fetch-registry: false # 如果为false 表示自己为注册中心
    service-url: # 监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置于Eureka Server交互的地址查询服务和注册服务都需要依赖这个defaultZone地址
